spring:
  datasource:                                             ## 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: Mysql8.0
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
#    password: puEYGSomuUP65KU6

# 开发环境 mybatis 打印日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl